#!/bin/bash

cc evolve.c -o evolve # For now

# Test run: Stop if parsing errors
if ! ./parse.py >/dev/null 2>&1
then
    echo >&2 "Failed to parse correctly"
    exit 1
fi

./parse.py | ./evolve

# vim: ft=sh
